##
# Server
##
server:
    port: 8081
    servlet:
        context-path: /oauth2-livraria-microservice


feign:
    client:
        config:
            livraria:
                LoggerLevel: full


logging.level.br.com.zup.edu.livrariaclient.client.LivrariaClient: DEBUG


##
# Client Credentials Flow
##

spring:
    security:
        oauth2:
            client:
                registration:
                    livraria:
                        client-id: oauth2-livraria-microservice
                        client-secret: AyELTe51FdTWFLlp4yU3vMNkHwVTtKkc
                        authorization-grant-type: client_credentials
                        scope: [livros:read, autores:read]
                provider:
                    livraria:
                        token-uri: http://localhost:18080/realms/livraria/protocol/openid-connect/token